In [78]:
from spam_data.feature_engineering import build_dataset

from sklearn.linear_model import LinearRegression
import pandas as pd

In [63]:
orig = build_dataset()

C:\Users\james\Documents\Capstone\sports_betting\james\spam_ml\.venv\lib\site-packages\spam_data\feature_engineering\utility_functions.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])


Season 2021-22: 1230 games
Season 2022-23: 1230 games
Season 2023-24: 860 games
Season 2021-22: 1222 games
Season 2022-23: 1221 games
Season 2023-24: 851 games


In [64]:
orig

GAME_ID  ROLL_HOME_PTS  ROLL_HOME_FGM  ROLL_HOME_FGA  ROLL_HOME_FG_PCT  \
0     22100001            NaN            NaN            NaN               NaN   
1     22100002            NaN            NaN            NaN               NaN   
2     22100004            NaN            NaN            NaN               NaN   
3     22100007            NaN            NaN            NaN               NaN   
4     22100012            NaN            NaN            NaN               NaN   
...        ...            ...            ...            ...               ...   
3289  22300820          108.4           42.6           92.6             0.460   
3290  22300829          125.0           48.2           87.8             0.548   
3291  22300830          105.2           39.4           85.0             0.465   
3292  22300828          109.8           41.6           89.2             0.468   
3293  22300831          125.0           47.0           90.6             0.520   

      ROLL_HOME_FG3M  ROLL_HOME_FG3A  ROLL_HOME_FG3_PCT  ROLL_HOME_FTM  \
0                NaN             NaN                NaN            NaN   
1                NaN             NaN                NaN            NaN   
2                NaN             NaN                NaN            NaN   
3                NaN             NaN                NaN            NaN   
4                NaN             NaN                NaN            NaN   
...              ...             ...                ...            ...   
3289            11.2            35.6              0.312           12.0   
3290            12.8            31.6              0.405           15.8   
3291            13.2            37.2              0.364           13.2   
3292            11.6            33.8              0.345           15.0   
3293            14.4            37.2              0.391           16.6   

      ROLL_HOME_FTA  ...      HOME_TEAM_NAME  AWAY_TEAM_ID  \
0               NaN  ...     Milwaukee Bucks    1610612751   
1               NaN  ...  Los Angeles Lakers    1610612744   
2               NaN  ...     Detroit Pistons    1610612741   
3               NaN  ...   Memphis Grizzlies    1610612739   
4               NaN  ...        Phoenix Suns    1610612743   
...             ...  ...                 ...           ...   
3289           16.6  ...  Washington Wizards    1610612739   
3290           20.2  ...      Indiana Pacers    1610612761   
3291           19.4  ...   Memphis Grizzlies    1610612751   
3292           17.0  ...     New York Knicks    1610612765   
3293           22.6  ...    Sacramento Kings    1610612748   

      AWAY_TEAM_ABBREVIATION         AWAY_TEAM_NAME  GAME_DATE  HOME_PTS  \
0                        BKN          Brooklyn Nets 2021-10-19       127   
1                        GSW  Golden State Warriors 2021-10-19       114   
2                        CHI          Chicago Bulls 2021-10-20        88   
3                        CLE    Cleveland Cavaliers 2021-10-20       132   
4                        DEN         Denver Nuggets 2021-10-20        98   
...                      ...                    ...        ...       ...   
3289                     CLE    Cleveland Cavaliers 2024-02-25       105   
3290                     TOR        Toronto Raptors 2024-02-26       122   
3291                     BKN          Brooklyn Nets 2024-02-26        86   
3292                     DET        Detroit Pistons 2024-02-26       113   
3293                     MIA             Miami Heat 2024-02-26       110   

      AWAY_PTS  GAME_RESULT  TOTAL_PTS  PLUS_MINUS  
0          104            1        231        23.0  
1          121            0        235        -7.0  
2           94            0        182        -6.0  
3          121            1        253        11.0  
4          110            0        208       -12.0  
...        ...          ...        ...         ...  
3289       114            0        219        -9.0  
3290       130            0        252        -8.0  
3291      

In [65]:
orig.columns

Index(['GAME_ID', 'ROLL_HOME_PTS', 'ROLL_HOME_FGM', 'ROLL_HOME_FGA',
       'ROLL_HOME_FG_PCT', 'ROLL_HOME_FG3M', 'ROLL_HOME_FG3A',
       'ROLL_HOME_FG3_PCT', 'ROLL_HOME_FTM', 'ROLL_HOME_FTA',
       'ROLL_HOME_FT_PCT', 'ROLL_HOME_OREB', 'ROLL_HOME_DREB', 'ROLL_HOME_REB',
       'ROLL_HOME_AST', 'ROLL_HOME_STL', 'ROLL_HOME_BLK', 'ROLL_HOME_TOV',
       'ROLL_HOME_PF', 'ROLL_AWAY_PTS', 'ROLL_AWAY_FGM', 'ROLL_AWAY_FGA',
       'ROLL_AWAY_FG_PCT', 'ROLL_AWAY_FG3M', 'ROLL_AWAY_FG3A',
       'ROLL_AWAY_FG3_PCT', 'ROLL_AWAY_FTM', 'ROLL_AWAY_FTA',
       'ROLL_AWAY_FT_PCT', 'ROLL_AWAY_OREB', 'ROLL_AWAY_DREB', 'ROLL_AWAY_REB',
       'ROLL_AWAY_AST', 'ROLL_AWAY_STL', 'ROLL_AWAY_BLK', 'ROLL_AWAY_TOV',
       'ROLL_AWAY_PF', 'SEASON_ID', 'HOME_TEAM_ID', 'HOME_TEAM_ABBREVIATION',
       'HOME_TEAM_NAME', 'AWAY_TEAM_ID', 'AWAY_TEAM_ABBREVIATION',
       'AWAY_TEAM_NAME', 'GAME_DATE', 'HOME_PTS', 'AWAY_PTS', 'GAME_RESULT',
       'TOTAL_PTS', 'PLUS_MINUS'],
      dtype='object')

In [85]:
season_id = orig.SEASON_ID.str.split('-').apply(lambda x: int(x[0]) - 2021)

In [86]:
season_id = orig.SEASON_ID.str.split('-').apply(lambda x: f"s{x[0]}")

In [66]:
feature_cols = ["ROLL_HOME_PTS", "ROLL_AWAY_PTS"]
target_col = ["TOTAL_PTS"]

In [119]:
df = orig[feature_cols + target_col].dropna()

In [120]:
pd.get_dummies(season_id)

s2021  s2022  s2023
0      True  False  False
1      True  False  False
2      True  False  False
3      True  False  False
4      True  False  False
...     ...    ...    ...
3289  False  False   True
3290  False  False   True
3291  False  False   True
3292  False  False   True
3293  False  False   True

[3294 rows x 3 columns]

In [121]:
df.join(pd.get_dummies(season_id))

ROLL_HOME_PTS  ROLL_AWAY_PTS  TOTAL_PTS  s2021  s2022  s2023
26            123.0           95.0        232   True  False  False
27            121.0          115.0        239   True  False  False
29             83.0           87.0        198   True  False  False
32            124.0          112.0        185   True  False  False
35            124.0          134.0        204   True  False  False
...             ...            ...        ...    ...    ...    ...
3289          108.4          113.0        219  False  False   True
3290          125.0          115.8        252  False  False   True
3291          105.2          111.8        197  False  False   True
3292          109.8          112.0        224  False  False   True
3293          125.0          111.4        231  False  False   True

[3181 rows x 6 columns]

In [122]:
df.head()

ROLL_HOME_PTS  ROLL_AWAY_PTS  TOTAL_PTS
26          123.0           95.0        232
27          121.0          115.0        239
29           83.0           87.0        198
32          124.0          112.0        185
35          124.0          134.0        204

In [123]:
df.dropna()

ROLL_HOME_PTS  ROLL_AWAY_PTS  TOTAL_PTS
26            123.0           95.0        232
27            121.0          115.0        239
29             83.0           87.0        198
32            124.0          112.0        185
35            124.0          134.0        204
...             ...            ...        ...
3289          108.4          113.0        219
3290          125.0          115.8        252
3291          105.2          111.8        197
3292          109.8          112.0        224
3293          125.0          111.4        231

[3181 rows x 3 columns]

In [124]:
expected = df["ROLL_HOME_PTS"] + df["ROLL_AWAY_PTS"]

In [125]:
expected

26      218.0
27      236.0
29      170.0
32      236.0
35      258.0
        ...  
3289    221.4
3290    240.8
3291    217.0
3292    221.8
3293    236.4
Length: 3181, dtype: float64

In [126]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

import math

In [127]:
df.TOTAL_PTS.values

array([232, 239, 198, ..., 197, 224, 231], dtype=int64)

In [128]:
math.sqrt(mean_squared_error(df["TOTAL_PTS"].values, expected))

20.145067366025458

In [129]:
df = df.join(pd.get_dummies(season_id))

In [130]:
df["ROLL_PTS_CROSS"] = df["ROLL_HOME_PTS"] * df["ROLL_AWAY_PTS"]

In [151]:
train_test_split?

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

trai

In [152]:
train_df, test_df = train_test_split(df, test_size=0.1)

In [153]:
train_df

ROLL_HOME_PTS  ROLL_AWAY_PTS  TOTAL_PTS  s2021  s2022  s2023  \
1681          119.8          112.0        223  False   True  False   
732           111.0          113.8        210   True  False  False   
1212          107.6          104.0        191   True  False  False   
1945          109.8          110.4        208  False   True  False   
375           107.6          110.6        234   True  False  False   
...             ...            ...        ...    ...    ...    ...   
642           116.4          120.4        228   True  False  False   
2874          122.2          119.0        234  False  False   True   
2042          124.6          119.4        247  False   True  False   
289            98.8          112.2        289   True  False  False   
2167          105.4          112.4        242  False   True  False   

      ROLL_PTS_CROSS  
1681        13417.60  
732         12631.80  
1212        11190.40  
1945        12121.92  
375         11900.56  
...              ...  
642         14014.56  
2874        14541.80  
2042        14877.24  
289         11085.36  
2167        11846.96  

[2862 rows x 7 columns]

In [154]:
test_df

ROLL_HOME_PTS  ROLL_AWAY_PTS  TOTAL_PTS  s2021  s2022  s2023  \
2120          112.8          109.6        206  False   True  False   
2247          119.6          115.4        230  False   True  False   
2102          110.2          109.4        214  False   True  False   
1394          125.0          115.8        243  False   True  False   
923           102.0          126.4        217   True  False  False   
...             ...            ...        ...    ...    ...    ...   
2764          126.6           96.4        254  False  False   True   
1987          115.4          117.0        259  False   True  False   
2958          120.4          120.8        265  False  False   True   
1918          124.6          119.2        200  False   True  False   
2982          120.8          105.6        196  False  False   True   

      ROLL_PTS_CROSS  
2120        12362.88  
2247        13801.84  
2102        12055.88  
1394        14475.00  
923         12892.80  
...              ...  
2764        12204.24  
1987        13501.80  
2958        14544.32  
1918        14852.32  
2982        12756.48  

[319 rows x 7 columns]

In [155]:
model = LinearRegression()

In [156]:
train_df[feature_cols].values

array([[119.8, 112. ],
       [111. , 113.8],
       [107.6, 104. ],
       ...,
       [124.6, 119.4],
       [ 98.8, 112.2],
       [105.4, 112.4]])

In [157]:
train_df[target_col].stack().values

array([223, 210, 191, ..., 247, 289, 242], dtype=int64)

In [158]:
model = LinearRegression()

In [146]:
RandomForestRegressor?

Init signature:
RandomForestRegressor(
    n_estimators=100,
    *,
    criterion='squared_error',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=1.0,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    bootstrap=True,
    oob_score=False,
    n_jobs=None,
    random_state=None,
    verbose=0,
    warm_start=False,
    ccp_alpha=0.0,
    max_samples=None,
    monotonic_cst=None,
)
Docstring:     
A random forest regressor.

A random forest is a meta estimator that fits a number of decision tree
regressors on various sub-samples of the dataset and uses averaging to
improve the predictive accuracy and control over-fitting.
Trees in the forest use the best split strategy, i.e. equivalent to passing
`splitter="best"` to the underlying :class:`~sklearn.tree.DecisionTreeRegressor`.
The sub-sample size is controlled with the `max_samples` parameter if
`bootstrap=True` (default), otherwise the whole dataset is use

In [164]:
model = RandomForestRegressor(oob_score=True)

In [165]:
model.fit(train_df.drop(columns=target_col).values, train_df[target_col].stack().values)

RandomForestRegressor(oob_score=True)

In [160]:
model.oob_score_

AttributeError: 'LinearRegression' object has no attribute 'oob_score_'

In [161]:
model.coef_

array([ 5.52947795e-01,  4.14841803e-01, -2.91675573e+00,  9.72542205e-01,
        1.94421353e+00, -3.24000452e-04])

In [162]:
model.intercept_

121.49770140367693

In [166]:
math.sqrt(mean_squared_error(test_df[target_col].stack().values, model.predict(test_df.drop(columns=target_col).values)))

20.71208186575413

In [49]:
model = LinearRegression(fit_intercept=False)

In [54]:
from sklearn.ensemble import RandomForestRegressor

In [62]:
model = RandomForestRegressor(n_estimators=100)

In [58]:
RandomForestRegressor?

Init signature:
RandomForestRegressor(
    n_estimators=100,
    *,
    criterion='squared_error',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=1.0,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    bootstrap=True,
    oob_score=False,
    n_jobs=None,
    random_state=None,
    verbose=0,
    warm_start=False,
    ccp_alpha=0.0,
    max_samples=None,
    monotonic_cst=None,
)
Docstring:     
A random forest regressor.

A random forest is a meta estimator that fits a number of decision tree
regressors on various sub-samples of the dataset and uses averaging to
improve the predictive accuracy and control over-fitting.
Trees in the forest use the best split strategy, i.e. equivalent to passing
`splitter="best"` to the underlying :class:`~sklearn.tree.DecisionTreeRegressor`.
The sub-sample size is controlled with the `max_samples` parameter if
`bootstrap=True` (default), otherwise the whole dataset is use